GRIF-209: refactor products-contains-component output and added --include-container-roots
RedHatProductSecurity/griffon pull request #281
Opened 2024-01-17 10:47 UTC by JimFuller-RedHat

a heavy refactor of output from services products-contains-components

|  verbosity  | product                 | root                    | child           | other                                       | comment|
|---------------------|-------------------------|-----------------------|----------------|----------------------------------------|-------------|
|                         | product version    | nvr                      |                                       |                            |      default verbosity using product versions         |
| **-v**                    | product stream     | nvr (type)            |  [ name {versions} ({types}), ... ]  |            | uses product streams  includes children summarising versions, types              |
| **-vv**                   | product stream    | nvr (type:arch)    |   [ name {versions} ({types}:{arches}), ... ] | related_url, build_source_url  | include children summarising versions, types, arches with urls |
| **-vvv**                 | product stream    | nvr (type:arch)    |   [ nvr (type:arch), ... ]  | related_url, build_source_url  | list each child using nvr (type:arch) |
| **-vvvv**               | product stream    | purl                     |   [purl, ... ]    | related_url, build_source_url  | list everything with purls |

where the **-v** and **-vv** options summarise versions, types and arches of children components. The **-vvv** option lists out each child component without summarising. The **-vvvv** option emits purls.

also 
* added a new flag, -**-include-container-roots**, as we now default exclude root containers from output.
* added a new flag, -**-exclude-unreleased**, to narrow down output to only released components.

2024-01-17 14:10 UTC, JakubFrejlach commented
Tested and it works great. Table nicely corresponds with the actual output. One problem might be when using middleware CLI from Griffon for Maven stuff I get:

```
    if obj["purl"] not in seen:
KeyError: 'purl'
```

Might need some special handling

2024-01-17 16:01 UTC, JakubFrejlach requested changes
Couple of questions and the `-r` render problem as per slack discussion

2024-01-17 16:04 UTC, JimFuller-RedHat commented on griffon/static/default_griffonrc
> +include_container_roots = False
yes just going with the status quo here, anything else seemed out of scope for this specific PR

2024-01-17 16:05 UTC, JimFuller-RedHat commented on griffon/services/core_queries.py
> -        "released_components": "True",
yes, I am doing some testing - I may have to put this and other limits in back in place if those tests show 504s

2024-01-17 16:05 UTC, JimFuller-RedHat commented on griffon/services/core_queries.py
> +            # search_all_params["released_components"] = "True"
correct, see last comment ... it may come back

2024-01-17 16:05 UTC, JimFuller-RedHat commented on griffon/services/core_queries.py
> +            # search_all_roots_params["released_components"] = "True"
same

2024-01-17 18:33 UTC, JimFuller-RedHat commented
-r works for me ex. griffon service products-contain-component -r 'webkit(2|3)gtk' -vv

2024-01-18 09:41 UTC, JakubFrejlach commented
> -r works for me ex. griffon service products-contain-component -r 'webkit(2|3)gtk' -vv

I would like to also verify this again once Corgi stage/prod performance issues are resolved.

2024-01-18 09:49 UTC, JakubFrejlach reviewed
LGTM! I would still like to verify the -r before the approval.

2024-01-18 11:39 UTC, JakubFrejlach approved these changes
LGTM!

2024-01-18 11:44 UTC, merged